export const REMOVE_SESSION = 'REMOVE_SESSION'
export const FETCH_USER = 'FETCH_USER'
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_CART = 'UPDATE_CART'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
